name: 'bd_data'
version: '1.0.0'
config-version: 2

profile: 'bd_data'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bd_analytics:
    +materialized: view
    1_staging:
      +schema: staging
      +tags: ["staging"]
      
    2_intermediate:
      +materialized: ephemeral
      +tags: ["intermediate"]
      
    3_marts:
      +materialized: table
      +schema: marts
      +tags: ["production"]